language: node_js
node_js:
  - "0.10"
## more information on configuring openshift deployments
## http://docs.travis-ci.com/user/deployment/openshift/
#deploy:
#  provider: openshift
#  # Configure these values on your TravisCI 'Repository Settings' page:
#  # http://docs.travis-ci.com/user/environment-variables/#Using-Settings
#  user: $OPENSHIFT_USERNAME
#  password: $OPENSHIFT_PASSWORD
#  app: $OPENSHIFT_APP_NAME
#  domain: $OPENSHIFT_APP_NAMESPACE
